name: dart_project_management_api
description: A powerful Dart API for seamless integration with Dart's AI-native project management platform. This package provides comprehensive tools for project management, task automation, and team collaboration, leveraging Dart's advanced AI capabilities.
version: 0.1.0+1
repository: https://github.com/alexandremaillot/dart_project_management_api
homepage: https://github.com/alexandremaillot/dart_project_management_api
documentation: https://pub.dev/documentation/dart_project_management_api
issue_tracker: https://github.com/alexandremaillot/dart_project_management_api/issues

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

# Additional metadata for pub.dev
topics:
  - project-management
  - ai
  - dart
  - flutter
  - productivity
  - task-management
  - team-collaboration

# License information
license: MIT
