name: dart_project_management_api
description: dart project management api
version: 0.1.0+1
publish_to: none
repository: https://github.com/alexandremaillot/dart_project_management_api

environment:
  sdk: ^3.5.0

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  http: ^1.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
